# Refactor Payload section, will now contain much more information

authentication = {
    'username':'xx',
    'password':'xx'
}

codes_for_quarters = {
    'SUMMER2017': '20173',
    'SPRING2017': '20172',
    'WINTER2017': '20171',
    'FALL2016': '20164',
    'SPRING2016': '20162',
    'WINTER2016': '20161',
    'FALL2015': '20154',
    'SUMMER2015': '20153',
    'SPRING2015': '20152',
    'WINTER2015': '20151',
    'FALL2014': '20144'
}

codes_for_subject = {
    'ANTH': 'ANTH ',
    'ART': 'ART  ',
    'ARTHI': 'ARTHI',
    'ARTST': 'ARTST',
    'ASAM': 'AS AM',
    'ASTRO': 'ASTRO',
    'BIO': 'BIOL ',
    'BMSE': 'BMSE ',
    'BLST': 'BL ST',
    'CHEMENG': 'CH E ',
    'CHEMBIO': 'CHEM ',
    'CHST': 'CH ST',
    'CHIN': 'CHIN ',
    'CLASS': 'CLASS',
    'COMM': 'COMM ',
    'COMLIT': 'C LIT',
    'CMPSC': 'CMPSC',
    'CMPTG': 'CMPTG',
    'CNCSP': 'CNCSP',
    'DANCE': 'DANCE',
    'DYNS': 'DYNS ',
    'EARTH': 'EARTH',
    'EACS': 'EACS ',
    'EEMB': 'EEMB ',
    'ECON': 'ECON ',
    'EDU': 'ED   ',
    'ECE': 'ECE  ',
    'ENGR': 'ENGR ',
    'ENGL': 'ENGL ',
    'ESM': 'ESM  ',
    'ENVST': 'ENV S',
    'ESS': 'ESS  ',
    'ES': 'ES   ',
    'FEMST': 'FEMST',
    'FAMST': 'FAMST',
    'FRENCH': 'FR   ',
    'GENST': 'GEN S',
    'GEOG': 'GEOG ',
    'GER': 'GER  ',
    'GPS': 'GPS  ',
    'GLOBL': 'GLOBL',
    'GRAD': 'GRAD ',
    'GREEK': 'GREEK',
    'HEB': 'HEB  ',
    'HIST': 'HIST ',
    'INT': 'INT  ',
    'ITAL': 'ITAL ',
    'JAPAN': 'JAPAN',
    'KOR': 'KOR  ',
    'LATIN': 'LATIN',
    'LATST': 'LAIS ',
    'LING': 'LING ',
    'LIT': 'LIT  ',
    'MARSC': 'MARSC',
    'MATRL': 'MATRL',
    'MATH': 'MATH ',
    'MENG': 'ME   ',
    'MAT': 'MAT  ',
    'MST': 'ME ST',
    'MEST': 'MES  ',
    'MS': 'MS   ',
    'MCDB': 'MCDB ',
    'MUS': 'MUS  ',
    'MPL': 'MUS A',
    'PHIL': 'PHIL ',
    'PHYS': 'PHYS ',
    'POLS': 'POL S',
    'PORTU': 'PORT ',
    'PSY': 'PSY  ',
    'RST': 'RG ST',
    'RENST': 'RENST',
    'SLAV': 'SLAV ',
    'SOC': 'SOC  ',
    'SPAN': 'SPAN ',
    'SHS': 'SHS  ',
    'PSTAT': 'PSTAT',
    'TMP': 'TMP  ',
    'THTR': 'THTR ',
    'WRIT': 'WRIT ',
    'WL': 'W&L  '
}


config = {
  "apiKey": "xx",
  "authDomain": "xx",
  "databaseURL": "xx",
  "storageBucket": "xx"
}
